import os

os.system('wget https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3/Hack.zip')
os.system('wget https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3/NerdFontsSymbolsOnly.zip')
os.system('unzip *.zip')
os.system('rm -rf *.zip')
os.system('sudo mv *.ttf /usr/local/share/fonts')
os.system('fc-cache -f -v')
os.system('sudo apt install zsh -y')
os.system('chsh -s $(which zsh)')
os.system('cp scripts/ubuntu/shells/zshrc ~/.zshrc')
os.system('sudo apt install zsh-syntax-highlighting zsh-autosuggestions locate bat -y')
os.system('sudo updatedb')
os.system('sudo mkdir /usr/share/zsh-sudo')
os.system('sudo chown $USER:$USER /usr/share/zsh-sudo')
os.system('wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh')
os.system('sudo mv sudo.plugin.zsh /usr/share/zsh-sudo')
os.system('wget https://github.com/Peltoche/lsd/releases/download/0.23.1/lsd-musl_0.23.1_amd64.deb')
os.system('sudo dpkg -i lsd-musl_0.23.1_amd64.deb')
os.system('mkdir -p ~/.local/bin')
os.system('rm lsd-musl_0.23.1_amd64.deb')
os.system('ln -s /usr/bin/batcat ~/.local/bin/bat')
os.system('git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k')
os.system('echo \'source ~/powerlevel10k/powerlevel10k.zsh-theme\' >>~/.zshrc')
os.system('cp scripts/ubuntu/shells/p10k.zsh ~/.p10k.zsh')
os.system('git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf')
os.system('~/.fzf/install')